BuscoBicoFrontEnd/Controllers/PrestadorController.cs
using BuscoBicoFrontEnd.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json;
using System.Net.Http.Headers;
namespace BuscoBicoFrontEnd.Controllers
{
    public class PrestadorController : Controller
    {
        string baseurl = "https://localhost:7111/";
        // GET: PrestadorController/ListarPrestador OK
        public async Task<IActionResult> ListarPrestador()
        {
            List<PrestadorModel>? prestadores = new List<PrestadorModel>();
            using (var httpClient = new HttpClient())
            {
                httpClient.BaseAddress = new Uri(baseurl);
                httpClient.DefaultRequestHeaders.Clear();
                httpClient.DefaultRequestHeaders.Accept.Add(
                    new MediaTypeWithQualityHeaderValue("application/json"));
                HttpResponseMessage response = await httpClient.GetAsync("api/Prestadores");
                if (response.IsSuccessStatusCode)
                {
                    var dados = response.Content.ReadAsStringAsync().Result;
                    prestadores = JsonConvert.DeserializeObject<List<PrestadorModel>>(dados);

                }
                return View(prestadores);
            }
        }

        // GET: PrestadorController/DetalharPrestador/5 OK
        public async Task<IActionResult> DetalharPrestador(int id)
        {
            
            PrestadorModel? prestador = new PrestadorModel();
            using (var httpClient = new HttpClient())
            {
                httpClient.BaseAddress = new Uri(baseurl);
                httpClient.DefaultRequestHeaders.Clear();
                httpClient.DefaultRequestHeaders.Accept.Add(
                    new MediaTypeWithQualityHeaderValue("application/json"));
                HttpResponseMessage responseMessage = await httpClient.GetAsync("api/Prestadores/" + id);
                if (responseMessage.IsSuccessStatusCode)
                {
                    var dados = responseMessage.Content.ReadAsStringAsync().Result;
                    prestador = JsonConvert.DeserializeObject<PrestadorModel>(dados);
                }
                responseMessage = await httpClient.GetAsync("api/Reviews/ReviewsDoPrestador/" + id);
                if (responseMessage.IsSuccessStatusCode)
                {
                    var dados = responseMessage.Content.ReadAsStringAsync().Result;
                    prestador.Reviews = JsonConvert.DeserializeObject<List<ReviewModel>>(dados);
                }
                else
                {
                    prestador.Reviews = new List<ReviewModel>();
                }
            }
            return View(prestador);
        }

        // GET: PrestadorController/CriarPrestador OK
        public ActionResult CadastrarPrestador()
        {
            return View();
        }

        // POST: PrestadorController/CriarPrestador OK
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CadastrarPrestador(PrestadorModel prestador)
        {
            prestador.Reviews = new List<ReviewModel>();            
            try
            {
                using(var httpClient = new HttpClient())
                {
                    HttpResponseMessage responseMessage = await httpClient.PostAsJsonAsync(
                        baseurl + "api/Prestadores", prestador);
                }
                return RedirectToAction(nameof(ListarPrestador));
            }
            catch
            {
                return View();
            }
        }

        // GET: PrestadorController/EditarPrestador/5 OK
        public async Task<IActionResult> EditarPrestador(int id)
        {
            PrestadorModel? prestador = new PrestadorModel();
            using (var httpClient = new HttpClient())
            {
                httpClient.BaseAddress = new Uri(baseurl);
                httpClient.DefaultRequestHeaders.Clear();
                httpClient.DefaultRequestHeaders.Accept.Add(
                    new MediaTypeWithQualityHeaderValue("application/json"));
                HttpResponseMessage responseMessage = await httpClient.GetAsync("api/Prestadores/" + id);
                if (responseMessage.IsSuccessStatusCode)
                {
                    var dados = responseMessage.Content.ReadAsStringAsync().Result;
                    prestador = JsonConvert.DeserializeObject<PrestadorModel>(dados);
                }
            }
            return View(prestador);
        }

        // POST: PrestadorController/EditarPrestador/5 OK
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditarPrestador(int id, PrestadorModel prestadorEditado)
        {
            try
            {
                PrestadorModel? prestador = new PrestadorModel();
                using (var httpClient = new HttpClient())
                {
                    httpClient.BaseAddress = new Uri(baseurl);
                    httpClient.DefaultRequestHeaders.Clear();
                    httpClient.DefaultRequestHeaders.Accept.Add(
                        new MediaTypeWithQualityHeaderValue("application/json"));
                    HttpResponseMessage responseMessage = await httpClient.GetAsync("api/Prestadores/" + id);
                    if (responseMessage.IsSuccessStatusCode)
                    {
                        var dados = responseMessage.Content.ReadAsStringAsync().Result;
                        prestador = JsonConvert.DeserializeObject<PrestadorModel>(dados);
                        prestador.Nome = prestadorEditado.Nome;
                        prestador.Telefone = prestadorEditado.Telefone;
                        prestador.Email = prestadorEditado.Email;
                        prestador.Localizacao = prestadorEditado.Localizacao;
                        prestador.Funcao = prestadorEditado.Funcao;
                        prestador.Descricao = prestadorEditado.Descricao;
                        prestador.PrecoDiaria = prestadorEditado.PrecoDiaria;
                        prestador.Reviews = new List<ReviewModel>();

                        responseMessage = await httpClient.PutAsJsonAsync(
                            baseurl + "api/Prestadores/" + id, prestador);
                    }
                }
                return RedirectToAction(nameof(ListarPrestador));
            }
            catch
            {
                return View();
            }
        }

        // GET: PrestadorController/DeletarPrestador/5 OK
        public async Task<IActionResult> DeletarPrestador(int id)
        {
            PrestadorModel? prestador = new PrestadorModel();
            using (var httpClient = new HttpClient())
            {
                httpClient.BaseAddress = new Uri(baseurl);
                httpClient.DefaultRequestHeaders.Clear();
                httpClient.DefaultRequestHeaders.Accept.Add(
                    new MediaTypeWithQualityHeaderValue("application/json"));
                HttpResponseMessage responseMessage = await httpClient.GetAsync("api/Prestadores/" + id);
                if (responseMessage.IsSuccessStatusCode)
                {
                    var dados = responseMessage.Content.ReadAsStringAsync().Result;
                    prestador = JsonConvert.DeserializeObject<PrestadorModel>(dados);
                }
            }
            return View(prestador);
        }

        // POST: PrestadorController/DeletarPrestador/5 OK
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeletarPrestador(int id, PrestadorModel prestadorApagando)
        {
            try
            {
                using(var httpClient = new HttpClient()) {
                    httpClient.BaseAddress = new Uri(baseurl);
                    httpClient.DefaultRequestHeaders.Clear();
                    httpClient.DefaultRequestHeaders.Accept.Add(
                        new MediaTypeWithQualityHeaderValue("application/json"));
                    HttpResponseMessage responseMessage = await httpClient.DeleteAsync("api/Prestadores/" + id);
                }
                return RedirectToAction(nameof(ListarPrestador));
            }
            catch
            {
                return View();
            }
        }
    }
}

BuscoBicoFrontEnd/Views/Prestador/CadastrarPrestador.cshtml
@model BuscoBicoFrontEnd.Models.PrestadorModel
@{
    ViewData["Title"] = "Cadastrar Prestador";
}
<h1>@ViewData["Title"]</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="CadastrarPrestador">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            
            <div class="form-group">
                <label asp-for="Nome" class="control-label">Nome</label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Telefone" class="control-label">Telefone</label>
                <input asp-for="Telefone" class="form-control" type="tel" />
                <span asp-validation-for="Telefone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label">E-mail</label>
                <input asp-for="Email" class="form-control" type="email"/>
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Localizacao" class="control-label">Localização</label>
                <input asp-for="Localizacao" class="form-control"/>
                <span asp-validation-for="Localizacao" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Funcao" class="control-label">Função</label>
                <input asp-for="Funcao" class="form-control" />
                <span asp-validation-for="Funcao" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Descricao" class="control-label">Descrição</label>
                <textarea asp-for="Descricao" class="form-control" rows="4"></textarea>
                <span asp-validation-for="Descricao" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PrecoDiaria" class="control-label">Valor da diária</label>
                <input asp-for="PrecoDiaria" class="form-control" type="number" />
                <span asp-validation-for="PrecoDiaria" class="text-danger"></span>
            </div>
            <div class="form-group">
                <br>
                <input type="submit" value="Cadastrar Prestador" class="btn btn-outline-dark" />
                <input type="reset" value="Limpar" class="btn btn-outline-dark" />
                <a class="btn btn-outline-dark" asp-controller="Home" asp-action="Index">Início</a>
            </div>
        </form>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

BuscoBicoFrontEnd/Views/Prestador/DeletarPrestador.cshtml
@model BuscoBicoFrontEnd.Models.PrestadorModel
@{
    ViewData["Title"] = "Deletar Prestador";
}
<h1>@ViewData["Title"]</h1>
<h3>O seguinte Prestador será removido, deseja continuar?</h3>
<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            Id:
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            Nome:
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt class = "col-sm-2">
            Telefone:
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Telefone)
        </dd>
        <dt class = "col-sm-2">
            E-mail:
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            Localização:
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Localizacao)
        </dd>
        <dt class = "col-sm-2">
            Função:
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Funcao)
        </dd>
        <dt class = "col-sm-2">
            Descrição:
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Descricao)
        </dd>
        <dt class = "col-sm-2">
            Valor da diária:
        </dt>
        <dd class = "col-sm-10">
            R$: @Html.DisplayFor(model => model.PrecoDiaria),00
        </dd>
    </dl>
    
    <form asp-action="DeletarPrestador">
        <hr />
        <input type="submit" value="Deletar Prestador" class="btn btn-outline-danger" /> 
        <a class="btn btn-outline-dark" asp-action="ListarPrestador">Voltar para a lista</a>
    </form>
</div>

BuscoBicoFrontEnd/Views/Prestador/DetalharPrestador.cshtml
@model BuscoBicoFrontEnd.Models.PrestadorModel
@{
    ViewData["Title"] = "Detalhes do Prestador";
}
<h1>@ViewData["Title"]</h1>
<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            Id:
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            Nome:
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt class = "col-sm-2">
            Telefone:
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Telefone)
        </dd>
        <dt class = "col-sm-2">
            E-mail:
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            Localização:
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Localizacao)
        </dd>
        <dt class = "col-sm-2">
            Função:
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Funcao)
        </dd>
        <dt class = "col-sm-2">
            Descrição:
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Descricao)
        </dd>
        <dt class = "col-sm-2">
            Valor da diária:
        </dt>
        <dd class = "col-sm-10">
            R$: @Html.DisplayFor(model => model.PrecoDiaria),00
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Editar Prestador", "EditarPrestador", new{ id = Model.Id }, new{@class="btn btn-outline-dark"})
    @Html.ActionLink("Deletar", "DeletarPrestador", new{ id = Model.Id },new{@class="btn btn-outline-dark"})
    <a class="btn btn-outline-dark" asp-action="ListarPrestador">Voltar para a lista</a>   
    <hr/>
</div>
<div>
    <h5 class="h5">Avaliações</h5>
</div>
<table class="table">
    <thead>
        <tr>
            <th>
                Autor
            </th>
            <th>
                Comentário
            </th>
            <th>
                Nota
            </th>
            <th>
                Ações
            </th>
        </tr>
    </thead>
    <tbody>
            @foreach (var review in Model.Reviews)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(autor => review.Autor.Nome) 
                    </td>
                    <td>
                        @Html.DisplayFor(comentario => review.Comentario)
                    </td>
                    <td>
                        @Html.DisplayFor(avaliacao => review.Avaliacao)
                    </td>
                    <td>
                    @Html.ActionLink("Editar","EditarReview", "Review",new {id=review.Id},new{@class="btn btn-sm btn-outline-dark"})
                    @Html.ActionLink("Deletar","DeletarReview", "Review", new {id=review.Id},new{@class="btn btn-sm btn-outline-dark"})
                    </td>
                </tr>
            }                   
    </tbody>
</table>
<div>
    @Html.ActionLink("Adicionar Avaliação","CadastrarReview","Review",new{id = Model.Id},new{@class="btn btn-outline-dark"})
    
</div>

BuscoBicoFrontEnd/Views/Prestador/EditarPrestador.cshtml
@model BuscoBicoFrontEnd.Models.PrestadorModel
@{
    ViewData["Title"] = "Editar Prestador";
}
<h1>@ViewData["Title"]</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <h6 class="text-dark">
            Editando Prestador @Html.DisplayFor(model => model.Nome) com Id @Html.DisplayFor(model => model.Id)
        </h6>
        <form asp-action="EditarPrestador">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nome" class="control-label">Nome:</label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Telefone" class="control-label">Telefone:</label>
                <input asp-for="Telefone" class="form-control" />
                <span asp-validation-for="Telefone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label">E-mail:</label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Localizacao" class="control-label">Localização:</label>
                <input asp-for="Localizacao" class="form-control" />
                <span asp-validation-for="Localizacao" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Funcao" class="control-label">Função:</label>
                <input asp-for="Funcao" class="form-control" />
                <span asp-validation-for="Funcao" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Descricao" class="control-label">Descrição:</label>
                <textarea asp-for="Descricao" class="form-control" rows="4"></textarea>
                <span asp-validation-for="Descricao" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PrecoDiaria" class="control-label">Valor da diária:</label>
                <input asp-for="PrecoDiaria" class="form-control" />
                <span asp-validation-for="PrecoDiaria" class="text-danger"></span>
            </div>
            <div class="form-group">
                <br>
                <input type="submit" value="Editar Prestador" class="btn btn-outline-dark" />
                <a class="btn btn-outline-dark" asp-action="ListarPrestador">Voltar para a lista</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

BuscoBicoFrontEnd/Views/Prestador/ListarPrestador.cshtml
@model IEnumerable<BuscoBicoFrontEnd.Models.PrestadorModel>
@{
    ViewData["Title"] = "Listar Prestadores";
}
<h1>@ViewData["Title"]</h1>
<p>
    <a class="btn btn-outline-dark" asp-controller="Prestador" asp-action="CadastrarPrestador">Cadastrar Prestador</a>
    <a class="btn btn-outline-dark" asp-controller="Home" asp-action="Index">Início</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                Id
            </th>
            <th>
                Nome
            </th>
            <th>
                Telefone
            </th>
            <th>
                E-mail
            </th>
            <th>
                Localização
            </th>
            <th>
                Função
            </th>
            <th>
                Descrição
            </th>
            <th>
                Val. Diária
            </th>
            <th>
                Ações
            </th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Telefone)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Localizacao)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Funcao)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Descricao)
            </td>
            <td>
                R$: @Html.DisplayFor(modelItem => item.PrecoDiaria),00
            </td>
            <td>
                    @Html.ActionLink("Editar", "EditarPrestador", new {  id=item.Id  },new{@class="btn btn-sm btn-outline-dark"})
                    @Html.ActionLink("Detalhes", "DetalharPrestador", new { id=item.Id },new{@class="btn btn-sm btn-outline-dark"})
                    @Html.ActionLink("Deletar", "DeletarPrestador", new {  id=item.Id  },new{@class="btn btn-sm btn-outline-dark"})
            </td>
        </tr>
}
    </tbody>
</table>